INSERT INTO categories (name) VALUES
('Tecnología'),
('Celulares y Telefonía'),
('Informática'),
('Electrodomésticos'),
('Audio, TV y Video'),
('Gaming'),
('Herramientas y Construcción'),
('Hogar y Deco'),
('Muebles'),
('Cocina'),
('Lavado y Planchado'),
('Climatización'),
('Iluminación'),
('Salud y Belleza'),
('Cuidado Personal'),
('Deportes y Fitness'),
('Aire Libre y Camping'),
('Bebés y Niños'),
('Juguetes'),
('Moda y Accesorios'),
('Mascotas'),
('Movilidad y Rodados'),
('Librería y Arte'),
('Seguridad para el Hogar'),
('Equipaje y Viajes'),
('Domótica'),
('Otros');
