name: Auto Tweet from Suggestions

on:
  schedule:
    - cron: '0 14,17,21,0 * * *'  # 11am, 2pm, 6pm, 9pm ART (GMT-3 → UTC+3)
  workflow_dispatch:

jobs:
  tweet:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      - name: Run auto tweet script
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
        run: |
          cd backend
          python random-tweet.py
