name: Run Fravega Scraper

on:
  workflow_dispatch:

jobs:
  run-scrapers:
    name: "Run Fravega scraper - ${{ matrix.part }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        part:
          - part1
          - part2

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium psycopg2-binary beautifulsoup4 python-dotenv

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable

    - name: Set CHROME environment variables
      run: |
        echo "CHROME_BIN=$(which google-chrome)" >> $GITHUB_ENV
        echo "PATH=$PATH:/usr/bin/google-chrome" >> $GITHUB_ENV

    - name: Run scraper script
      env:
        DBNAME: ${{ secrets.DBNAME }}
        DBUSER: ${{ secrets.DBUSER }}
        DBPASSWORD: ${{ secrets.DBPASSWORD }}
        DBHOST: ${{ secrets.DBHOST }}
        DBPORT: ${{ secrets.DBPORT }}
      run: |
        cd scrapers
        if [ "${{ matrix.part }}" = "part1" ]; then
          echo "Ejecutando parte 1 (hasta indumentaria)"
          python get-fravega-1-products.py || echo "Script failed with exit code $?"
        else
          echo "Ejecutando parte 2 (el resto de categorías)"
          python get-fravega-2-products.py || echo "Script failed with exit code $?"
        fi

    - name: Upload error log if it exists
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: scraper-errors-fravega-${{ matrix.part }}
        path: scrapers/scraper_errors_fravega-${{ matrix.part }}.log
        if-no-files-found: ignore
